### ISSUE TITLE
SDE Notifications

### ISSUE THREAD

**Issue by colcrunch** [colcrunch/killbot#5]
Figure out a way to determine if the SDE is out of date, and let the bot owner know that they should update it.

**Comment by ddavaham** [comment]
Last Modified Date on the files in https://www.fuzzwork.co.uk/dump/latest/

**Comment by colcrunch** [comment]
For now this will be done by sending bot owner a message whenever the bot has to hit esi to get a type id. (limited to 1 notification per day)
